[mysqld]
# avvia il processo come utente 'mysql', non come root.
user = mysql

# File che contiene l'ID del processo (utile per comandi di stop/restart).
pid-file = /var/run/mysqld/mysqld.pid

# file per le connessioni locali tramite socket, script.sh ne ha bisogno per connettersi
socket = /var/run/mysqld/mysqld.sock

# mariadb apre la porta 3306 per le connessioni remote
port = 3306

# directory per l`installazione di mariadb
basedir = /usr

# directory dove sono salvati i database
datadir = /var/lib/mysql
tmpdir = /tmp

# directory per i file di log
lc-messages-dir = /usr/share/mysql

# file per gli errori
log_error = /var/log/mysql/error.log

# di default maridb ascolta in local host (127.0.0.1) ma per permettere connessioni remote
# bisogna cambiare il bind-address a 0.0.0.0 cosi che ascolti tutti gli indirizzi
bind-address = 0.0.0.0

query_cache_size = 16M

# tempo limite dopo la quale i file vengono rimossi
expire_logs_days = 5

# caratteri e regole di confronto di default utilizzate da wordpress
character-set-server = utf8mb4

# Regole di confronto "Case Insensitive" (A == a) per utf8mb4. 
collation-server = utf8mb4_general_ci
