# utente con cui gira il processo nginx
user www-data;

# numero di worker
worker_processes auto;

pid /run/nginx.pid;

# includi i moduli abilitati dal sistema
include /etc/nginx/modules-enabled/*.conf;

events {
    worker_connections 768;
}

# blocco HTTP principale
# contiene le impostazioni condivise per tutti i server (virtual hosts)
http {

    sendfile on;                 # usa sendfile() per trasferire file
    tcp_nopush on;               # raggruppa i pacchetti per ridurre overhead
    tcp_nodelay on;              # disabilita Nagle per ridurre latenza
    keepalive_timeout 65;        # timeout per connessioni keep-alive
    types_hash_max_size 2048;    # dimensione hash per tipi MIME

    # tipi MIME e tipo di default per file sconosciuti
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    # qui si abilitano i protocolli TLS
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;

    # percorsi dei log di accesso ed errore
    access_log /var/log/nginx/access.log;
    error_log /var/log/nginx/error.log;

    # gzip (compressione delle risposte) ottimizza il tutto come creare i file .zip ma sul web
    gzip on;

    server {
        listen 443 ssl;
        listen [::]:443 ssl;

        server_name ftersill.42.fr;

        ssl_certificate /etc/nginx/ssl/inception.crt;
        ssl_certificate_key /etc/nginx/ssl/inception.key;

        # root del sito (punto di mount del volume con WordPress)
        root /var/www/html;
        # gestione pagine wordpress
        index index.php index.html index.htm;

        # location per la radice del sito
        # try_files cerca il file richiesto, poi la directory, altrimenti 404
        location / {
            try_files $uri $uri/ =404;
        }

        # gestione delle richieste PHP
        location ~ \.php$ {
            # Carica configurazione standard per FastCGI
            include snippets/fastcgi-php.conf;

            # Invia le richieste PHP al servizio 'wordpress' (php-fpm) sulla porta 9000
            fastcgi_pass wordpress:9000;
        }
    }
}